### ISSUE TITLE
RVIZ - Planning Scene warning: requesting initial scene failed

### ISSUE THREAD

**Issue by Robeatrice** [AIRLab-POLIMI/ros2-igus-rebel#1]
Hello,

i am working on programming the IGUS REBEL KID with 4 Axis via ROS2. So your repository gives me hope of reaching my goal. 
I have never worked with rviz before, so i am quite new to it. 

Hello
i am working on programming the IGUS REBEL KID with 4 Axis via ROS2.Since I am new to ROS2 and IGUS i want to try to publish a joint trajectory message.

I followed your explanation. Unfortunatly I got some errors, so I had to clone scout_nav2 and aruco_interfaces package. Also I had to change error_code_to_string in aruco_follower, aruco_toucher, commander, manipulator_action_server and I had to delete igus_rebel_servo because I couldn't get rid of the errors. 

Now I got to get it through colcon build without any errors and I could do the launch: 
 "ros2 launch igus_rebel_moveit_config demo.launch.py"

I get this Error: [rviz2-1] [ERROR] [1715803979.997183884] [rviz2.moveit.ros.background_processing]: Exception caught while processing action 'Frame::changePlanningGroup': std::future_error: Broken promise

And in RVIZ i get the error of requesting initial scene failed

![image](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/assets/149628653/d6968e9a-598a-48a2-ae7b-3aab9830513f)

Can you help me? Why do I get this error?  Thank you so much !

I am using Linux Ubuntu 22.04
ROS2 Iron
on a Virtual Machine

**Comment by SimonGiampy** [comment]
Hi, I'm sorry that you are having issues with my code.
First of all, this repository contains code customized for the robot in my laboratory, therefore with customized URDF description files, a gripper end effector, and other code used for testing and controlling the robot via code. This implies that you will have to remove the parts that are not necessary for your setup, and change the ones that are not working. Otherwise, you can check out the official ros2 repository for the Igus Rebel, developed by Commonplace Robotics, also available on Github. Nevertheless, it's challenging to get these robots to work with MoveIt2, and it's really not easy to change and adjust the code to your configuration.

You mentioned you are working with the Igus Rebel KID. This repository does not contain the URDF description for that robot, in fact, I'm using the 6DoF version. You will have to replace all URDF and XACRO macros with the corrected URDF file that you need. You can find it in the official repository. My suggestion is to create a workspace with the essential files and packages, and then adding the rest to fix your configuration.

The `igus_rebel_hw_controller` package should work correctly also for the KID robot, but minor adjustments may be required since your robot has 4 joints instead of 6. the package `igus_rebel_moveit_config` can be also useful for you, given that you remove or change correctly the launch file parameters. I use many parameters since my configuration is highly customized for different cameras and end-effectors.

The package `igus_rebel_description_ros2` is almost entirely useless for you because again I use a different robot. And the description files must match the robot that you use otherwise you get nasty errors that may be difficult to solve.

The compilation errors that you found may be due to the different version of MoveIt2 library that you use. Between different builds and releases they change some pieces of code, creating those compilation issues that you encountered.

Regarding the error 
> I get this Error: [rviz2-1] [ERROR] [1715803979.997183884] [rviz2.moveit.ros.background_processing]: Exception caught while processing action 'Frame::changePlanningGroup': std::future_error: Broken promise

I never encountered this issue, and without access to your code, or the console log of the launch file, I can't help you. Try removing everything that is not essential, and leaving only the description, hw_controller, and moveit_config packages, and fix the issues step-by-step until you get it to work at least in simulation. Let me know if you need further assistance.

**Comment by SimonGiampy** [comment]
Closing as stale since no further comment was provided
