### ISSUE TITLE
igus_rebel_description_ros2: typo in new XACRO argument

### ISSUE THREAD

**Issue by why371323** [AIRLab-POLIMI/ros2-igus-rebel#2]
After updating your repository, when executing the ros2 launch igus_rebel_moveit_config demo.launch.py command, I encountered the following error. How can I resolve it?
![32a1a08d7680cb70919756ca77a7b2d](https://github.com/AIRLab-POLIMI/ros2-igus-rebel/assets/49426430/06628b5b-3972-4ed9-bdb2-30d4c35320d1)

**Comment by SimonGiampy** [comment]
Hi, thanks for the feedback. Due to a typo in the last commit, a bug prevents to load the URDF properly. I added a box in the "castle", the structure holding the sensors on the mobile robot where the Igus Rebel arm is mounted. You can always set `load_base:=false` to prevent the loading of the mobile base. Anyways, I will update the code and fix this issue later today.
